const test=require("node:test");const assert=require("node:assert/strict");
const{createTeam}=require("../game-engine");const{createGame,currentId,play,challenge,tick,publicState,score,confirmFinish,CARD_COUNTS,DECK_SIZE,HAND_SIZE,FINISH_BONUSES}=require("../liar-engine");
function setup(n=3){const teams=Array.from({length:8},(_,i)=>createTeam(i));for(let i=0;i<n;i++)teams[i].players.push({id:`p${i}`,nickname:`Đội ${i+1}`});return{teams,game:createGame(teams,{now:1000})}}
function card(id,category,type="private"){return{id,type,category,name:id,short:id,icon:"x",desc:"test"}}
test("các đội đánh lần lượt theo chiều kim đồng hồ",()=>{const{game}=setup(3),a=game.seats[0],b=game.seats[1];game.economies[a].hand=[card("a","growth"),card("a2","growth")];assert.equal(currentId(game),a);assert.equal(play(game,a,["a"],1100).ok,true);assert.equal(currentId(game),b)});
test("mỗi đội chỉ nhận bài riêng và host không thấy bài",()=>{const{game}=setup(2),a=game.seats[0],b=game.seats[1],host=publicState(game),pa=publicState(game,a);assert.equal(host.hand,null);assert.equal(pa.hand.length,8);assert.equal(pa.economies[b].hand,undefined);assert.equal(pa.economies[b].handCount,8)});
test("bộ bài hữu hạn 70 lá, chia 8 lá mỗi đội và dư 6",()=>{const{game}=setup(8);assert.equal(DECK_SIZE,70);assert.equal(HAND_SIZE,8);assert.deepEqual(CARD_COUNTS,{private:11,state:8,fdi:10,coop:11,public:7,social:10,tax:7,balance:6});assert.equal(game.deck.length,6);assert.equal(Object.values(game.economies).reduce((n,e)=>n+e.hand.length,0),64)});
test("ba nhóm mục tiêu là 21 21 22 và có 6 Joker",()=>{assert.deepEqual([CARD_COUNTS.private+CARD_COUNTS.fdi,CARD_COUNTS.coop+CARD_COUNTS.social,CARD_COUNTS.state+CARD_COUNTS.public+CARD_COUNTS.tax,CARD_COUNTS.balance],[21,21,22,6])});
test("mọi đội bắt đầu 100 mỗi chỉ số và đánh bài không đổi chỉ số",()=>{const{game}=setup(2),a=game.seats[0],e=game.economies[a],before={...e.stats},id=e.hand[0].id;assert.deepEqual(before,{gdp:100,budget:100,welfare:100,stability:100});play(game,a,[id],1100);assert.deepEqual(e.stats,before);assert.equal(score(e),400)});
test("host chỉ thấy số lá đã úp, không thấy nội dung",()=>{const{game}=setup(2),a=game.seats[0],ids=game.economies[a].hand.slice(0,2).map(c=>c.id);play(game,a,ids,1100);const pub=publicState(game);assert.equal(pub.pile[0].count,2);assert.equal(pub.pile[0].cards,undefined)});
test("nói dối ở lá cuối bị bắt: bài mất, vẫn về đích nhưng chịu khủng hoảng",()=>{const{game}=setup(2),[a,b]=game.seats;game.economies[a].hand=[card("lie","welfare")];play(game,a,["lie"],1100);assert.equal(game.pendingFinish,a);const r=challenge(game,b,1200);assert.equal(r.truthful,false);assert.equal(r.loserId,a);assert.equal(game.economies[a].hand.length,0);assert.equal(game.economies[a].place,1);assert.equal(game.economies[a].crises.length,1);assert.ok(score(game.economies[a])<500)});
test("nói thật ở lá cuối được xác nhận về nhất và cộng 25 mỗi chỉ số",()=>{const{game}=setup(2),[a,b]=game.seats;game.economies[a].hand=[card("truth","growth")];play(game,a,["truth"],1100);const r=challenge(game,b,1200);assert.equal(r.truthful,true);assert.equal(game.economies[a].place,1);assert.equal(game.economies[a].finishBonus,25);assert.deepEqual(game.economies[a].stats,{gdp:125,budget:125,welfare:125,stability:125})});
test("đánh tiếp đồng nghĩa xác nhận người trước về đích",()=>{const{game}=setup(3),[a,b]=game.seats;game.economies[a].hand=[card("last","growth")];game.economies[b].hand=[card("next","growth"),card("stay","growth")];play(game,a,["last"],1100);const result=play(game,b,["next"],1200);assert.equal(result.confirmed.teamId,a);assert.equal(game.economies[a].place,1)});
test("còn hai đội thì người sau bắt buộc tố, không được đánh tiếp",()=>{const{game}=setup(2),[a,b]=game.seats;game.economies[a].hand=[card("last","growth")];const bid=game.economies[b].hand[0].id;play(game,a,["last"],1100);assert.equal(publicState(game,b).forcedChallenge,true);const blocked=play(game,b,[bid],1150);assert.equal(blocked.ok,false);assert.match(blocked.message,/bắt buộc tố/i);const result=challenge(game,b,1200);assert.equal(result.ok,true);assert.equal(game.placements.length,2)});
test("thưởng bốn hạng lần lượt 25 18 12 7",()=>{const{game}=setup(5);for(let i=0;i<4;i++)confirmFinish(game,game.seats[i],1100+i);assert.deepEqual(game.placements.map(x=>x.bonus),[25,18,12,7]);assert.deepEqual(FINISH_BONUSES,{1:25,2:18,3:12,4:7})});
test("bảng tổng kết đánh dấu đúng bốn đội điểm cao nhất",()=>{const{game}=setup(8);for(let i=0;i<8;i++){game.economies[game.seats[i]].stats={gdp:100-i,budget:100-i,welfare:100-i,stability:100-i}}const board=publicState(game).leaderboard;assert.equal(board.filter(x=>x.qualified).length,4);assert.deepEqual(board.slice(0,4).map(x=>x.teamId),game.seats.slice(0,4))});
test("tám đội có thể đánh hết bài và trận tự kết thúc",()=>{const{game}=setup(8);let guard=0;while(game.phase!=="finished"&&guard++<40){if(game.phase==="reveal"){tick(game,game.reveal.endsAt);continue}const id=currentId(game),pub=publicState(game,id);if(pub.forcedChallenge)challenge(game,id,3000+guard);else play(game,id,game.economies[id].hand.slice(0,3).map(c=>c.id),2000+guard)}assert.equal(game.phase,"finished");assert.equal(game.placements.length,8);assert.deepEqual(game.placements.slice(0,4).map(x=>x.bonus),[25,18,12,7]);assert.equal(publicState(game).leaderboard.filter(x=>x.qualified).length,4)});
