const test=require("node:test");const assert=require("node:assert/strict");
const{createTeam}=require("../game-engine");const{createGame,currentId,play,challenge,publicState,score,effect,CARD_COUNTS,DECK_SIZE,HAND_SIZE}=require("../liar-engine");
function setup(n=3){const teams=Array.from({length:8},(_,i)=>createTeam(i));for(let i=0;i<n;i++)teams[i].players.push({id:`p${i}`,nickname:`Đội ${i+1}`});return{teams,game:createGame(teams,{now:1000})}}
function card(id,category,type="private"){return{id,type,category,name:id,short:id,icon:"x",desc:"test",delta:{gdp:2,budget:1,welfare:0,stability:0}}}
test("các đội ngồi và đánh lần lượt theo chiều kim đồng hồ",()=>{const{game}=setup(3),a=game.seats[0],b=game.seats[1];game.economies[a].hand=[card("a","growth")];assert.equal(currentId(game),a);assert.equal(play(game,a,["a"],1100).ok,true);assert.equal(currentId(game),b)});
test("mỗi đội chỉ nhận được bài riêng, host không thấy bài",()=>{const{game}=setup(2),a=game.seats[0],b=game.seats[1],host=publicState(game),pa=publicState(game,a);assert.equal(host.hand,null);assert.equal(pa.hand.length,5);assert.equal(pa.economies[b].hand,undefined);assert.equal(pa.economies[b].handCount,5)});
test("bộ bài hữu hạn 40 lá và chia hết cho 8 đội",()=>{const{game}=setup(8);assert.equal(DECK_SIZE,40);assert.equal(HAND_SIZE,5);assert.deepEqual(CARD_COUNTS,{private:6,state:4,fdi:6,coop:6,public:4,social:6,tax:4,balance:4});assert.equal(game.deck.length,0);assert.equal(Object.values(game.economies).reduce((n,e)=>n+e.hand.length,0),40)});
test("ba nhóm mục tiêu có 12 lá và chỉ 4 lá cân bằng",()=>{const growth=CARD_COUNTS.private+CARD_COUNTS.fdi,welfare=CARD_COUNTS.coop+CARD_COUNTS.social,regulation=CARD_COUNTS.state+CARD_COUNTS.public+CARD_COUNTS.tax;assert.deepEqual([growth,welfare,regulation,CARD_COUNTS.balance],[12,12,12,4])});
test("đánh được đúng 1 đến 3 lá và host chỉ thấy số lượng",()=>{const{game}=setup(2),a=game.seats[0],ids=game.economies[a].hand.slice(0,2).map(c=>c.id);assert.equal(play(game,a,ids,1100).ok,true);const pub=publicState(game);assert.equal(pub.pile[0].count,2);assert.equal(pub.pile[0].cards,undefined)});
test("tố đúng: người nói dối nhận khủng hoảng",()=>{const{game}=setup(2),[a,b]=game.seats;game.economies[a].hand=[card("lie","welfare")];play(game,a,["lie"],1100);const r=challenge(game,b,1200);assert.equal(r.truthful,false);assert.equal(r.loserId,a);assert.equal(game.economies[a].crises.length,1)});
test("tố sai: người tố nhận khủng hoảng",()=>{const{game}=setup(2),[a,b]=game.seats;game.economies[a].hand=[card("truth","growth")];play(game,a,["truth"],1100);const r=challenge(game,b,1200);assert.equal(r.truthful,true);assert.equal(r.loserId,b);assert.equal(game.economies[b].crises.length,1)});
test("GDP bỏ xa an sinh tạo trạng thái bất bình đẳng",()=>{assert.equal(effect({stats:{gdp:90,budget:60,welfare:30,stability:60},marketPower:0,statePower:0,fdi:0,domestic:0,publicSpend:0,taxCapacity:0}).id,"inequality")});
test("hai chế độ tính người thắng khác nhau",()=>{const rich={stats:{gdp:100,budget:90,welfare:20,stability:20},domestic:0},balanced={stats:{gdp:65,budget:65,welfare:65,stability:65},domestic:3};assert.ok(score(rich,"capitalist")>score(balanced,"capitalist"));assert.ok(score(balanced,"socialist")>score(rich,"socialist"))});
